### ISSUE TITLE
Updated Firebase Platform Interfaces

### ISSUE THREAD

**Issue by TimWhiting** [fluttercommunity/firebase_dart_sdk#26]
Hi @long1eu ,

First, I want to thank you for this. I'm glad the community sees the importance of desktop support for Firebase even if the official plugins aren't focusing on it.

Just wondering if you had plans / expected timeframe for supporting the updated platform interfaces for FirebaseCore/FirebaseAuth/CloudFirestore, after the updates that happened recently there: https://github.com/FirebaseExtended/flutterfire/issues/2582

I'd normally be willing to help with some pull requests, but unfortunately I don't have much free time right now & I'm not very familiar with the code. So I wouldn't be able to get to it for a couple months probably, and wondered if you were planning on updating it sometime sooner.

Thanks again!

**Comment by long1eu** [comment]
The plan was from the start to provide a way to use it with the federated plugins. So the new changes will the reflected. Right now firebase_core uses the new platform interface.

**Comment by TimWhiting** [comment]
Ah, thanks; I see the update is in the develop branch which I hadn't looked at. Thanks again, will be watching this repo, and will contribute if I can find time!
