### ISSUE TITLE
Does cloud firestore implementation support listening to changes

### ISSUE THREAD

**Issue by guyluz11** [fluttercommunity/firebase_dart_sdk#27]
As the readme is empty I was wondering if the cloud firestore implementation here support listening to changes in firestore documents.

**Comment by long1eu** [comment]
https://github.com/fluttercommunity/firebase_dart_sdk/tree/master/cloud_firestore/cloud_firestore_vm

**Comment by long1eu** [comment]
try develop branch, master is not up to date

**Comment by guyluz11** [comment]
Does it use google's official auth package or REST-based

**Comment by long1eu** [comment]
None of those. I provides a way for you to provide a token. Or it can use any this plugins https://github.com/fluttercommunity/firebase_dart_sdk/tree/develop/firebase_auth

**Comment by long1eu** [comment]
So to answer your initial question this supports listening.

**Comment by guyluz11** [comment]
Can it run with native dart code without flutter?.
