### ISSUE TITLE
google-services json vs Firebase options

### ISSUE THREAD

**Issue by parammittal162** [fluttercommunity/firebase_dart_sdk#33]
Hi all I am trying to get my apiKey and firebase databse URL remove from google-services json due to some security reasons. So is there any way I can remove them from json and keep in FirebaseOptions({...})

Tried to keep them here but got thir error -

![image](https://user-images.githubusercontent.com/62284007/119192401-bab52e80-ba9d-11eb-9de7-d2c2fcf7fba9.png)

Thanks in advanced

BTW
My Flutter configs

[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_GB.UTF-8)

**Comment by parammittal162** [comment]
@long1eu any ideas ??

**Comment by long1eu** [comment]
@parammittal162 I come with bad news for now. Unfortunately I can no longer maintain this repo and can't help you in this regard since it will require a feature that we don't have right now, if Im not mistaken.

**Comment by parammittal162** [comment]
can u tag somebody who can better help for the question ? Thanks a lot :+1:

**Comment by long1eu** [comment]
Unfortunately I was the only on work on this.

**Comment by parammittal162** [comment]
ok thanks a lot
